create table genders (
  id bigint generated by default as identity primary key,
  name text not null
);

create table users (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users,
  firstname text not null,
  lastname text not null, 
  thirdname text,
  birthdate date not null,
  gender bigint not null references genders
);

INSERT INTO "public"."genders" ("id", "name") VALUES 
('1', 'Мужской'), 
('2', 'Женский');